# Generated by Django 4.1.2 on 2022-10-31 02:41

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Comentario',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nombre_usuario', models.CharField(max_length=50)),
                ('fecha_comentario', models.DateField(default=None)),
                ('ingreso_comentario', models.TextField(max_length=1000)),
            ],
        ),
    ]
