# Generated by Django 4.1.2 on 2022-11-03 00:17

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Categoria',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nombre', models.CharField(max_length=200)),
                ('descripcion', models.CharField(max_length=200)),
            ],
        ),
        migrations.CreateModel(
            name='Publicacion',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('titulo', models.CharField(max_length=200)),
                ('descripcion', models.CharField(max_length=200)),
                ('contenido', models.CharField(max_length=200)),
                ('fecha_publicacion', models.DateField()),
                ('hashtag', models.CharField(max_length=200)),
                ('autor', models.CharField(max_length=200)),
                ('categoria', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='core.categoria')),
            ],
        ),
        migrations.CreateModel(
            name='Comentario',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('users', models.CharField(max_length=50)),
                ('fecha_comentario', models.DateField(auto_now_add=True)),
                ('ingreso_comentario', models.CharField(max_length=200)),
                ('publicacion_comentario', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='core.publicacion')),
            ],
        ),
    ]
