# Generated by Django 4.1.2 on 2022-11-24 10:21

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('blog', '0003_remove_post_imagen'),
    ]

    operations = [
        migrations.AddField(
            model_name='post',
            name='imagen_portada',
            field=models.ImageField(blank=True, default='default.jpg', null=True, upload_to='images/'),
        ),
    ]
