# Generated by Django 4.1.2 on 2022-11-24 10:22

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('blog', '0004_post_imagen_portada'),
    ]

    operations = [
        migrations.AlterField(
            model_name='post',
            name='avatar',
            field=models.ImageField(default='default.jpg', null=True, upload_to='avatars/'),
        ),
    ]
